
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.17.1"
    ports:
      - "9200:9200"
    environment:
      "discovery.type": "single-node"
      "xpack.security.enabled": "false"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    image: "docker.elastic.co/kibana/kibana:8.17.1"
    ports:
      - "5601:5601"
    environment:
      "ELASTICSEARCH_HOSTS": "http://elasticsearch:9200"
    depends_on:
      - elasticsearch
